dependencies
dependencies
	"Answer a Collection of package release IDs for the SqueakMap packages Trike depends on."
	"To find the GUID to put in this list, open a SqueakMap Package Loader and navigate to the RELEASE, not the package, you want to add.  Then explore that IndentingListItemMorph.  Because of an oddity with the object explorer, you can get the number you want by selecting the root object and printing self id in the bottom pane."

	^#(
		"'377aed01-76f2-4e2f-9336-a8565f4860e6' needsWork" "click for keyboard focus r1"
		'7339e3d0-16fe-490b-bab1-355c2026ca8f'	"YAXO 2.2"
		"Grid Layout"
		'b57421d1-7446-4139-b03a-b96d4349f0d8'	"Lockdown 1"
	) 
